import type { TranscriptionRecord, TranscriptionStats } from './types';

export const TRANSCRIPTION_RECORD_FIXTURE: TranscriptionRecord = {
  id: 42,
  file_name: 'episode.mp3',
  relative_path: 'podcasts/episode.mp3',
  text: '原始逐字稿',
  formatted_text: '排版后的逐字稿',
  language: 'zh',
  provider: 'mimo',
  engine: '',
  model: 'mimo-v2.5-asr',
  context: '',
  usage: null,
  task_id: 'transcribe-test',
  file_size_bytes: 128,
  audio_duration_seconds: 12,
  processing_seconds: 3,
  content_mode: 'standard',
  structure_status: 'unavailable',
  summary_status: 'not_started',
  summary_error: '',
  speaker_scope: '',
  diarization_status: '',
  speaker_count: 0,
  diarization_conflicts: 0,
  asr_diagnostics: {},
  asr_warnings: [],
  summary_model: '',
  summary_updated_at: null,
  claims_status: 'not_started',
  claims_error: '',
  claims_model: '',
  claims_updated_at: null,
  podcast_name: '',
  episode_title: '',
  guest_names: [],
  source_url: '',
  published_at: '',
  topic_tags: [],
  created_at: '2026-07-22T00:00:00.000Z',
  updated_at: '2026-07-22T00:00:00.000Z',
};

export const TRANSCRIPTION_STATS_FIXTURE: TranscriptionStats = {
  total_count: 1,
  total_file_size_bytes: 128,
  total_audio_duration_seconds: 12,
  total_text_chars: 6,
  total_processing_seconds: 3,
};
